#!/bin/sh

DTO_NAME=gpio_btn_bbb
DTBO_NAME=BBB-GPIO-BTN
#build_dtoverlay()
#{
#echo "dtc -@ -I dts -O dtb -o ${DTO_NAME}.dtbo ${DTO_NAME}.dts || exit 1"
#dtc -@ -I dts -O dtb -o ${DTBO_NAME}.dtbo ${DTO_NAME}.dts || exit 1
#ls -l ${DTBO_NAME}.dtbo
#sudo cp ${DTO_NAME}.dtbo /boot/firmware/
#echo "built and copied"
#ls -l /boot/firmware/${DTO_NAME}.dtb
#}


#--- 'main'
#build_dtoverlay #&& {

sudo cp ${DTO_NAME}.dtb /boot/dtbs/$(uname -r)/overlays/${DTBO_NAME}.dtbo
sync
ls -l /boot/dtbs/$(uname -r)/overlays/${DTBO_NAME}.dtbo
exit 0
